spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: dev@sagitta
    password: password@sagitta

#management:
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
#
#logging:
#  config: classpath:log/logback-dev.xml
#
#loki:
#  distributor:
#    url: http://localhost:3100/loki/api/v1/push
